apiVersion: v1
kind: Service
metadata:
    name: movies-service
spec:
  selector:
    app: movies
  ports:
    - port : 80     # service
      targetPort: 5000 #container
      nodePort: 30000 #cluster
  type: NodePort